# Configuración básica de Geyser para Railway
bedrock:
  # Usar el mismo puerto que Java
  port: 25565
  address: 0.0.0.0
  
remote:
  # Conectar al servidor local
  address: 127.0.0.1
  port: 25565
  
# Permitir conexiones desde cualquier versión
force-resource-packs: false
